# _config.yaml
title: Hani Alshikh Helm Charts
description: A chart repo for all Hani Alshikh Helm Charts.
theme: jekyll-theme-hacker
url: "https://charts.alshikh.de"
repo_name: H-S

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
